### ISSUE TITLE
Design Wireframes for Landing Page

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-community-portal#1]
We need basic layout guidance on the land page. A general concept will help make sure we're in the ballpark of what's needed.

Include 
- [x]  Sticky navigation
- [x]  Horizontal sections with subsections

**Comment by andycochran** [comment]
[Wireframe sketches](https://docs.google.com/drawings/d/1f1plkUyL2GqI7Uk6MV3bzCsHnj7Y3DPqEFmuKhOZrgE/edit)
