### ISSUE TITLE
Park access percentage

### ISSUE THREAD

**Issue by kerrygathers** [NYCPlanning/labs-community-portal#115]
The park access indicator is written as a fraction instead of percentage, causing it to display incorrectly. That's my fault for being inconsistent in the original CSV.

![image](https://user-images.githubusercontent.com/29131366/29221271-299b520e-7e8c-11e7-8a27-82f5065c2554.png)

**Comment by allthesignals** [comment]
I think this is resolved with the newest data, right? @kerrygathers
