### ISSUE TITLE
"Community Needs" are opinions, needs clear indication that they're non-facts

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-community-portal#124]
I feel it'd be helpful if it's clear that community needs are opinions of the community board, not NYC Planning. Considering call to action to contact community board?

**Comment by andycochran** [comment]
Does #161 address this well enough?

**Comment by amirapu** [comment]
Also linked to 172

**Comment by allthesignals** [comment]
The language has been changed to "perceived issues" - I think that addresses this issue
