### ISSUE TITLE
Want to search in the land use map for an address

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-community-portal#133]
I want to be able to find a particular parcel in the land use map by address

**Comment by chriswhong** [comment]
Should be an address search with autocomplete.  When a hit is selected, intersect with CD boundaries and navigate to the correct CD

**Comment by chriswhong** [comment]
Add a pin on the map, let it persist

**Comment by chriswhong** [comment]
User begins typing into search box.
Treat text the same way we do now, returning matches based on CD name or neighborhood name.  
If there are no results from the initial string matching, send the text to the mapzen search API and display autocomplete results.

Obviously, handle click differently depending on whether the results are from string match or autocomplete.

**Comment by allthesignals** [comment]
Plan A: integrate and merge Mapzen address search typeahead results into CD filter dropdown; match CD filters first, then append address search results

Plan B: turn on built-in Mapbox address search
