### ISSUE TITLE
I want to click on facilities map to filter by type;

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-community-portal#135]
There are a lot of facilities; I want to filter by type

**Comment by allthesignals** [comment]
Or, link the legend items to link to the facilities explorer with a filtered view

**Comment by chriswhong** [comment]
Recommend this site as an overview and not invest in complex UI for facilities... The facilities explorer should provide the more advanced functionality

**Comment by jorgeh01** [comment]
Resolved with link to Facilities Explorer
