### ISSUE TITLE
I would like to see a full list of needs statements

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-community-portal#140]
- Hook-up real data, pulling in complete list of available, known needs statements
 - User interface for selecting one of the needs statements; exposes full list of statements

**Comment by andycochran** [comment]
From where should we pull this data?

**Comment by jorgeh01** [comment]
What would be the best way to format this for you? We have FY2017-FY1983. Not all boards have a submission for each year.  Currently it's on our G Drive.

**Comment by allthesignals** [comment]
@jorgeh01 thinking about this - ideally we'd have a CSV spreadsheet linking CD with the filename of the PDF. How are they organized on the G drive? The problem is when some years are missing. There are a few ways to attack this problem.

**Comment by allthesignals** [comment]
@jorgeh01 @andycochran suggested putting them all on Github - that could work. We could have a separate repo that your team has access to. When updates come out, you can drag and drop files into the appropriate repo. Organized by boro & cd ids would be ideal. 

(There is a contents API that will help: https://developer.github.com/v3/repos/contents/)

**Comment by jorgeh01** [comment]
@allthesignals Both would work on our end. I'll take a look at the contents API and get back to you with any questions.

**Comment by jorgeh01** [comment]
@allthesignals looked through the API... and would definately need a walk through to get familiar with the different specifics. That being said, files from FY1983 - FY2018 are ready t0 be shared

**Comment by allthesignals** [comment]
@jorgeh01 we discussed this and decided to put everything into a repo and use the contents API to act as a tree for looking up available documents. We're going back to 2007.

**Comment by andycochran** [comment]
@allthesignals Would it help if I started a branch for this and prototyped a UI for listing dozens of links?

**Comment by andycochran** [comment]
We should maybe merge #161 first, to avoid an ugly merge.

**Comment by allthesignals** [comment]
@andycochran yes - thanks!

**Comment by allthesignals** [comment]
@andycochran can I start on this? Do you have a branch pulled down for it?

**Comment by andycochran** [comment]
On it now. Gimme a few min…

**Comment by andycochran** [comment]
Branch: `140-needs-statements`
