### ISSUE TITLE
Add Tooltip to Indicators for sourcing + additional info

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-community-portal#146]

**Comment by allthesignals** [comment]
@kerrygathers @amirapu how should we tackle this? Where do we want tooltips / what should they say?

**Comment by kerrygathers** [comment]
@allthesignals @amirapu I think each indicator title should have an "i" icon in superscript. I'll draft some text for each and post on slack for feedback.

**Comment by kerrygathers** [comment]
@allthesignals @chriswhong The latest CSV includes unique tooltip language for each CD for the ACS indicators: poverty, educational attainment, rent burden, mean commute, and unemployment.

Here's the tooltip language for the other indicators:

Crime Rate: NYPD Complaint Data, 2016
Street Cleanliness: New York City Department of Sanitation, 2017
Access to Parks: New York City Department of Parks & Recreation, 2016
