### ISSUE TITLE
Add Limited English Proficiency Indicator

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-community-portal#147]
To be defined by customer

**Comment by andycochran** [comment]
@kerrygathers We need to get this data into Carto.

**Comment by allthesignals** [comment]
@andycochran I think we can just use dummy data - any ideas about how the chart should look and feel?

**Comment by allthesignals** [comment]
This is plug and play - as soon as the column is available, I can drop it into the view as an indicator + chart

**Comment by jorgeh01** [comment]
Uploaded  an updated CSV file with all indicators, etc. on Slack "CD Profile Data... 20170824"
