### ISSUE TITLE
Add margins of error to bar chart hover tips

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-community-portal#149]
We need to add margins of error to the visualizations; @kerrygathers to provide data and advise on disclaimer

**Comment by allthesignals** [comment]
@kerrygathers should we touch base on the data updates?

**Comment by allthesignals** [comment]
@kerrygathers provided a link here: https://nycplanning.slack.com/files/kgathers/F6QMHN40P/cd_profile_data_with_moe_20170816.csv

**Comment by andycochran** [comment]
![image](https://user-images.githubusercontent.com/409279/29426095-8933e246-8353-11e7-8e71-8fb99fa8cf22.png)

**Comment by allthesignals** [comment]
I've switched over the data. Thanks @andycochran
