### ISSUE TITLE
Community Portal doesn't work on Internet Explorer

### ISSUE THREAD

**Issue by amirapu** [NYCPlanning/labs-community-portal#163]
Most CBs and govt. agencies only use IE as a browser

**Comment by chriswhong** [comment]
I loaded the site using IE on our browsers.  The home page loads, along with the map, but any attempt at navigating to a profile page results in `'fetch' is undefined` error in the console.  We probably need a polyfill to get this working.

**Comment by allthesignals** [comment]
@kerrygathers mentioned the same:" The page loads in IE, but I'm not getting the graphs, the land use map, or the facilities map"

@chriswhong where did you test this?

**Comment by allthesignals** [comment]
@hadekoyaDCP we need Browerstack to test this - thanks!

**Comment by chriswhong** [comment]
Polyfilled in 27f61e3d57c562f174a88a8d36d415ec5f904016, closing
