### ISSUE TITLE
[Documentation] Bower is a prerequisite 

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-community-portal#17]
I didn't need to install PhantomJS, as noted in the README. But I did need Bower, which isn't noted. Running `bower install` should also be added to the installation steps. Or maybe automate `bower install` after `npm install` with a post install script?

**Comment by allthesignals** [comment]
Thanks for pointing this out - this will also affect the buildpack during deployment, so we should think about it some. In general, we shouldn't use bower, but some of the 3rd party dependencies still require it to manage packages.

**Comment by allthesignals** [comment]
This is no longer a prereq
