### ISSUE TITLE
Reset District bounds on within-district geocode

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-community-portal#177]
@andycochran:
Once an address is plotted on the map, there's no feedback as to what the point's address is. There's also no way to remove it from the map; it's there until you search again. Perhaps instead of adding a point to the map, we add a popup that contains the address? The popup can be closed with the X button. And when you search a new address (or filter the typeahead text?), the popup disappears.

**Comment by jorgeh01** [comment]
Will resolved in ZoLa
