### ISSUE TITLE
Reorder Indicators

### ISSUE THREAD

**Issue by kerrygathers** [NYCPlanning/labs-community-portal#183]
Based @amirapu and my discussion with the press office, the order of the indicators should be:

Rent Burden | Park Access
Mean Commute | Street Cleanliness
Crime Rate | Educational Attainment
Unemployment | Poverty

**Comment by andycochran** [comment]
Closed by https://github.com/NYCPlanning/labs-community-portal/commit/5d2c972b1a7a87c78018bc1ff12ce9ea198806b4
