### ISSUE TITLE
Update content in "Projects" section

### ISSUE THREAD

**Issue by jorgeh01** [NYCPlanning/labs-community-portal#184]
Content for "Projects in your district" section found here: https://docs.google.com/document/d/14xBXYn-JZoyWVxj9RYZMdZR31Oam56udXRHauCfv5UE/edit

Content provided for:
LUCATS
Neighborhood Studies
CPC Hearings
197-a Plans
RSS feed for CB events

**Comment by allthesignals** [comment]
Related to #204
