### ISSUE TITLE
Move Community Assets next to facilities map

### ISSUE THREAD

**Issue by kerrygathers** [NYCPlanning/labs-community-portal#200]
- [ ] Remove colors
 - [x] Move this next to facilities map

**Comment by andycochran** [comment]
@allthesignals I see the section has been moved. But what was meant by "remove colors"? Has that been addressed? Or was it just feedback we're not going to implement? If this is referring to the colored icons, I like them FWIW.

**Comment by allthesignals** [comment]
@andycochran ah, maybe I forgot that part - I was addressing the main title of the issue. The custom wants to remove the color from the icons. Sorry about that.

**Comment by chriswhong** [comment]
Moot, closing
