### ISSUE TITLE
Add Tooltips to community assets

### ISSUE THREAD

**Issue by kerrygathers** [NYCPlanning/labs-community-portal#202]
Each should have a tooltip explaining what is being counted

Remove high schools, explain schools included, and consider disclaimer that attendance boundaries are not coterminus with CDs. Related to listing school districts in issue #83

**Comment by allthesignals** [comment]
@kerrygathers I think I just need some tooltip content for this:
 - Public Schools
 - Public Libraries
 - Hospitals and Clinics
 - Parks

**Comment by jorgeh01** [comment]
Just to be clear, will we be able to remove high schools? The facilities explorer's lowest subcategory in that area is public K-12 Schools

**Comment by kerrygathers** [comment]
@allthesignals @jorgeh01 @amirapu Arundathi and I talked to Sarah Whitham about it yesterday, and we're going to stick with the same numbers, but explain the definitions of each category in the tooltip. Tooltip language will be done today.

**Comment by jorgeh01** [comment]
Community Assets Tooltips 

**Public Schools**: Public elementary, middle, and high schools. Public schools identified may serve multiple Community Districts

**Public Libraries**: Libraries operated by NYPL, QPL, BPL and academic institutions

**Hospitals and Clinics**: Urgent care hospitals, diagnostic and treatment centers, and school-based health facilities

**Parks**: Properties operated by NYC Parks, NYC DOT, NYS Office of Parks, Recreation and Historic Preservation, NYS Dept. of Conservation, and City-State corporations and trusts
