### ISSUE TITLE
Add LUCATS projects

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-community-portal#204]
Add first page of LUCATS project results as a list, scrape in real time from DCP LUCATs app.

**Comment by chriswhong** [comment]
This has been roughly implemented in the branch `cw-lucats-list`, needs styling @andycochran .

![labscommunityportal_](https://user-images.githubusercontent.com/1833820/29574961-0a502f7a-8731-11e7-9e7a-4695381473ad.png)

We created a [microservice](https://github.com/NYCPlanning/labs-lucats-proxy) that scrapes the live LUCATS site (on-demand) and converts the results to JSON for each community district.

**Comment by andycochran** [comment]
@chriswhong I've styled the LUCATS subsection and pushed to your branch. I changed the header to "Recent Land Use Applications" and removed the bit about there being 20 of them, as some CDs do not have twenty. (I also made the Needs Statement subsection style match.)

**Comment by chriswhong** [comment]
Discovered an issue where the links to LUCATS would not work because they require an existing LUCATS session.  Workaround was to link to the print view for an application, which does not require a session.

Closed in
