### ISSUE TITLE
Add Neighborhood Studies Subsection

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-community-portal#205]
Customer to assist with data creation, list all studies relevant to the current CD, link to existing pages on DCP website

**Comment by kerrygathers** [comment]
@allthesignals CSV with relevant studies for each CD shared on slack. Note that some CDs have none. I think the CDs with no studies should get a note saying _No recent or ongoing studies_, and all CDs should get get a link below the list of studies that says _See more studies in your borough_ and links to:

Manhattan: http://www1.nyc.gov/site/planning/plans/manhattan.page
Bronx: http://www1.nyc.gov/site/planning/plans/bronx.page
Brooklyn: http://www1.nyc.gov/site/planning/plans/brooklyn.page
Queens: http://www1.nyc.gov/site/planning/plans/queens.page
Staten Island: http://www1.nyc.gov/site/planning/plans/staten-island.page
