### ISSUE TITLE
Add Zoning Subsection

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-community-portal#206]
Includes: 
- Zoning Map with tooltip
- Some snapshot of Zoning types in the current CD...   TBD

**Comment by allthesignals** [comment]
This goes under projects

**Comment by chriswhong** [comment]
The mapboxGL styles for a zoning layer are already in use in the capital planning platform, you can copy them from here: 
https://github.com/NYCPlanning/capital-planning-platform/blob/master/app/janelayers/zoning/ZoningJaneLayer.jsx

**Comment by chriswhong** [comment]
SQL for the vector tiles: SELECT *, LEFT(zonedist, 2) as primaryzone FROM support_zoning_zd

**Comment by chriswhong** [comment]
Commercial overlays are a separate dataset: SELECT * FROM support_zoning_co.  If you want to get fancy with it you can create one vector tile source with both layers in it.

**Comment by allthesignals** [comment]
@chriswhong how should the distribution chart work? Right now I'm using this query: 
`SELECT *, LEFT(overlay, 2) as primaryzone FROM support_zoning_co UNION ALL SELECT *, LEFT(zonedist, 2) as primaryzone FROM support_zoning_zd`

I could find the top 10 zones and show those?
