### ISSUE TITLE
Improve tooltip

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-community-portal#21]
Right now, tooltip is fixed to the centroid of geometry over which user mouseovers. It should follow mouse cursor and update as it cursor mouses over another geometry boundary.

**Comment by andycochran** [comment]
The current tooltip has a link within it. But it's impossible to click on. We should either avoid links in tooltips OR have them not follow the cursor and stay visible on hover-off long enough to click the links (something that behaves like Foundation's [Dropdown](http://foundation.zurb.com/sites/docs/dropdown.html) would work).

**Comment by allthesignals** [comment]
Moot, closing
