### ISSUE TITLE
Resources: Links to Demographic Data

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-community-portal#211]
This needs to be added; content from client

**Comment by allthesignals** [comment]
I think this will be a CSV?

**Comment by jorgeh01** [comment]
The majority if these resources will be links but there are a few maps that we create that will need to be "hosted"
Whats the best way to deal with maps that do not have links?

**Comment by jorgeh01** [comment]
Uploaded CSV on Slack. MIssing links to maps that will be created this week.

**Comment by allthesignals** [comment]
@jorgeh01 thanks - found it.

**Comment by chriswhong** [comment]
This was implemented in #243.  This issue was called "links to static maps" but the data provided was links to PUMA-level census data.  Is there more static map content? Closing for now

**Comment by jorgeh01** [comment]
@chriswhong Yes, there will be more static map content that will eaither need to be hosted on git or linked through the DCP server.
