### ISSUE TITLE
Resources: Add 197-A Plans subsection

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-community-portal#213]
This will look just like the LUCATS project subsection. Need data from customer @kerrygathers

**Comment by jorgeh01** [comment]
Two CSV files uploaded on Slack:

1. All 197-a Plans adopted
2. Implementation of 197-a Plans through rezoning initiatives

Both files contain "CD_Show" column for pulling into appropriate profile; 
-"Comprehensive Manhattan Waterfront Plan" will show on all Manahttan CDs
-"New Waterfront Revitalization Program" will be shown on all 59 CDs

**Comment by chriswhong** [comment]
213-197-a-plans

**Comment by chriswhong** [comment]
First pass implemented in f4b19ed7c01b77c7fa08d6300d592568446584a2.  Added another table in carto since the schema was different from the other plans, but may want to combine into a single table for easier maintenance.
