### ISSUE TITLE
Description below each section header

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-community-portal#214]
Some content from @kerrygathers - how exactly do we want to deal with the PUMA issue for Indicators?

**Comment by jorgeh01** [comment]
@allthesignals Content created for subsections:

https://docs.google.com/document/d/1fUTCRkUTkz19K0B8GN98Q_8w-vA_f1Ai5dlOKQqst0Y/edit

**Comment by andycochran** [comment]
Closed by https://github.com/NYCPlanning/labs-community-portal/commit/775a8e1f56c66bdafd2ab0795b2aaf64177ee289
