### ISSUE TITLE
Get Foundation JS to work

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-community-portal#23]
I tried following the Ember CLI Foundation docs to use Foundation's Javascript features. 

I added this to options: 
```js
    'ember-cli-foundation-6-sass': {
      'foundationJs': 'all'
    }
```

…which worked, kinda. Running `$(document).foundation();` in the console will init Foundation components. But there seems to be a timing issue, as indicated in https://github.com/acoustep/ember-cli-foundation-6-sass/issues/25.

We need to figure out the right hook to init Foundation. 

If we're gonna do it per component, there's a way to selectively initialize them:
```js
$('#foo').foundation();
```

See http://foundation.zurb.com/sites/docs/javascript.html#initializing for more on initializing Foundation plugins.

**Comment by allthesignals** [comment]
Prioritizing this, as it's block @andycochran on #7
