### ISSUE TITLE
Add sliding scale graph for LEP

### ISSUE THREAD

**Issue by amirapu** [NYCPlanning/labs-community-portal#230]

**Comment by jorgeh01** [comment]
Updated CSV containing Limited English Proficiency numbers with the following fields:
LEP_RATE
MOE_LEP_RATE
LEP_RATE_BORO
MOE_LEP_RATE_BORO
LEP_RATE_NYC
MOE_LEP_RATE_NYC

**Comment by jorgeh01** [comment]
@andycochran @chriswhong

**Comment by andycochran** [comment]
There's a PR for this… 
https://github.com/NYCPlanning/labs-community-portal/pull/294

Customer is looking into the text that goes with ("X% of residents self-identify as having limited English proficiency"). Can update via separate PR once decided.
