### ISSUE TITLE
Scroll-(back)-to misbehaves in IE11

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-community-portal#248]
Scroll (down) to works correctly, but hitting an action that needs to scroll back up to the appropriate section on causes it to scroll down slightly.

**Comment by allthesignals** [comment]
I can't debug this with current wifi speed

**Comment by allthesignals** [comment]
Addressed in #f2547f04

**Comment by chriswhong** [comment]
We lost scroll-to, the currently used navigation is from db7bdd676ed681807b39ee7ca0e769f788973a30

Closing for now, but if we want to scroll to sections this issue may rear its head again.
