### ISSUE TITLE
Zoning chart loads wrong CD

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-community-portal#260]
if you switch to another CD while a chart is loading, the previous CDs chart loads.

**Comment by chriswhong** [comment]
Need to cancel pending API call if route changes

**Comment by allthesignals** [comment]
I can look into this after prioritizing waterfront section

**Comment by allthesignals** [comment]
This will probably need JS concurrency to canceling pending network requests: https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop
