### ISSUE TITLE
All CB web/email links are disabled

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-community-portal#264]

**Comment by chriswhong** [comment]
`cb_website` and `cb_email` used to be columns in the main table, now they are gone...  @jorgeh01 can you work on getting them added back in?

**Comment by jorgeh01** [comment]
@chriswhong  is there an easy way to update the file in Carto instead of resharing the master csv? if not, i will share master csv

**Comment by allthesignals** [comment]
@chriswhong is moving this data into version control which will address this issue

**Comment by jorgeh01** [comment]
@chriswhong @allthesignals data is ready when you are!

**Comment by chriswhong** [comment]
@jorgeh01 I just added the two columns to the table in carto... the links are working now.  Thanks!
