### ISSUE TITLE
Link to EDC/HPD plans in "Neighborhood Studies & Plans" subsection

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-community-portal#268]

**Comment by chriswhong** [comment]
This will not include links to specific plans, but will just be a link with a call to action to check out EDC's plans

**Comment by allthesignals** [comment]
For HPD, I can find this: http://www1.nyc.gov/site/hpd/community/neighborhood-plans.page. 

Not sure what to use for EDC... link to their division? https://www.nycedc.com/division/planning-development-transportation. Or studies? https://www.nycedc.com/resources/economic-research-analysis.

**Comment by andycochran** [comment]
- EDC: https://www.nycedc.com/projects/all
- HPD: http://www1.nyc.gov/site/hpd/community/neighborhood-plans.page
