### ISSUE TITLE
Add i icon w/ cite info to Land Use apps, Studies/Plans, and 197a

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-community-portal#270]

**Comment by andycochran** [comment]
@amirapu @jorgeh01 @kerrygathers If one of y'all can write up the content for these, I can rig them up to work.

**Comment by jorgeh01** [comment]
READY! https://docs.google.com/document/d/14xBXYn-JZoyWVxj9RYZMdZR31Oam56udXRHauCfv5UE/edit

Can also past text here if thats easier

**Comment by andycochran** [comment]
This content is rather long for tooltips — which also cannot contain links:

<img src="https://user-images.githubusercontent.com/409279/29852412-f478e6ce-8d07-11e7-9ef3-959c7bc4f6e0.png" width=300>

**Comment by andycochran** [comment]
I've added the LUCATS tooltip, putting the link in the section description.

**Comment by jorgeh01** [comment]
@andycochran UPDATED content in section and "tried" adding tooltips to Neighborhood Studies and Plans + Community-Based Plans (changed 197-a to Community-Based Plans) in upcoming PR
