### ISSUE TITLE
Racial Breakdown Subsection

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-community-portal#276]
Noncomparative bar chart

**Comment by allthesignals** [comment]
Is this ready? Or waiting for data?

**Comment by allthesignals** [comment]
@kerrygathers is this already in the data profile? How should this look and where does it go? I assume indicators. cc @andycochran @chriswhong

**Comment by kerrygathers** [comment]
@allthesignals The data are in the table:

pct_white_nh = White (Non-Hispanic)
pct_black_nh = Black (Non-Hispanic)
pct_asian_nh = Asian (Non-Hispanic)
pct_other_nh = Other Race (Non-Hispanic)
pct_hispanic = Hispanic (of any race)

We didn't talk about the specific design this chart, but I'm think a horizontal bar with five segments. Any more specific thoughts, @amirapu @jorgeh01 @chriswhong @andycochran ?

I think the chart should go near the top of the indicators, along with the population pyramid.

**Comment by allthesignals** [comment]
Thanks for the quick response @kerrygathers! I'd like to know a little bit more about how this should look, I think we will just crib colors from another project @chriswhong did.
