### ISSUE TITLE
Density Subsection

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-community-portal#279]
Big Number

**Comment by andycochran** [comment]
I don't see the data for this. Is it 2010 population ÷ land mass? Can we nix the acres and put it there?

**Comment by chriswhong** [comment]
I think so, but defer to the customer.  I think the issue is what to use as the denominator, but we can start with that.

**Comment by allthesignals** [comment]
@kerrygathers @amirapu @jorgeh01 Where should this go? Do we have the data for it?

**Comment by kerrygathers** [comment]
@andycochran @chriswhong I added density to the new version of the static profiles, and did just what you suggested. Drop acres, add, population/square mile
[CD Profile - General Redesign_101.pdf](https://github.com/NYCPlanning/labs-community-portal/files/1268268/CD.Profile.-.General.Redesign_101.pdf)

**Comment by allthesignals** [comment]
Alright - thanks @kerrygathers. Is there a data update step in Carto?

**Comment by allthesignals** [comment]
@kerrygathers I think if we can just figure out which columns to use, we can add this. Thanks!

**Comment by kerrygathers** [comment]
@allthesignals is the land mass section getting square miles from the carto table? Should I add a column to it for density that's 2010 pop/square mile?

**Comment by andycochran** [comment]
See note in https://github.com/NYCPlanning/labs-community-portal/commit/7001c8cce5acee2625ba880a84964a5fa4a1eb95#comments
