### ISSUE TITLE
Add Population Pyramid

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-community-portal#280]

**Comment by andycochran** [comment]
One thing that makes this more complicated than just grabbing an existing D3 pop pyramid is that we have margin of error data to visualize.

**Comment by andycochran** [comment]
Would be nice to show the boro/city averages like this…
<img src="http://www.who.int/entity/bulletin/volumes/90/10/BLT-11-100750-F2.jpg">

**Comment by andycochran** [comment]
https://stackoverflow.com/questions/25044997/creating-population-pyramid-with-d3-js

**Comment by andycochran** [comment]
Let's also not make this pink & blue. 🙄

The indicators section already has a key for Estimate/MOE. We should just use grey bars with blue margin of error, same as the ranking charts. We can clearly label the sides male/female.

**Comment by andycochran** [comment]
New branch w/ layout for this: `280-population-pyramid`

**Comment by andycochran** [comment]
See note in https://github.com/NYCPlanning/labs-community-portal/commit/7001c8cce5acee2625ba880a84964a5fa4a1eb95#comments

**Comment by allthesignals** [comment]
Relevant columns: 
female_under_5
female_5_9
female_10_14
female_15_19
female_20_24
female_25_29
female_30_34
female_35_39
female_40_44
female_45_49
female_50_54
female_55_59
female_60_64
female_65_69
female_70_74
female_75_79
female_80_84
female_85_over
male_under_5
male_5_9
male_10_14
male_15_19
male_20_24
male_25_29
male_30_34
male_35_39
male_40_44
male_45_49
male_50_54
male_55_59
male_60_64
male_65_69
male_70_74
male_75_79
male_80_84
male_85_over

MOEs prefix with `moe_`

**Comment by allthesignals** [comment]
![Screen Shot 2017-09-01 at 10.43.03 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5830e3bc40b5a00e00a5b4c0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772a6454f26b7191a379ef0c2f52415f4dbc30254d58eeb9cb74fce36f34985619e8d86a0972933b19a9ba8118bd50ba208e4782b0b9d84b96fa2137a5dad11b61435c52dcbd4f3fb29843c259f34be54f52a3133662e273376e0a.png)

**Comment by allthesignals** [comment]
Right now, the chart isn't updating properly. There is a committed hack that's deployed for presentation, but it should be undone. The hack is to tear down the chart on component willUpdate hook.
