### ISSUE TITLE
Add "special age"  comparative charts

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-community-portal#281]
Children and Seniors

**Comment by andycochran** [comment]
Need data in model.

**Comment by andycochran** [comment]
We have the data now. But there are a ton of columns for male/female age ranges. I assume those are meant to be used for the Population Pyramid (#280). Need clarification as to what these "special age" indicators should be. 
/cc @kerrygathers @jorgeh01 @amirapu

**Comment by jorgeh01** [comment]
@andycochran the "Special age" indicators are the following:

Under 18: "UNDER18_RATE"
Over 65: "OVER65_RATE"

The male/female ranges are for the Population Pyramid.
