### ISSUE TITLE
Add links to static maps

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-community-portal#283]
New subsection next to census data tables

**Comment by andycochran** [comment]
Needs content. 
/ping @amirapu @kerrygathers @jorgeh01

**Comment by jorgeh01** [comment]
@andycochran finalzing content. Will have the following maps:

1. 2010 Census Tracts within CD (1 per district)
2. Political Boundaries within CD (1 per borough)
3. CD Base Map (1 per district)

**Comment by allthesignals** [comment]
@jorgeh01 let us know when ready - thanks!

**Comment by jorgeh01** [comment]
@allthesignals just to be clear, i'm adding the maps to "https://github.com/NYCPlanning/labs-cd-needs-statements" 

or should I create a new "folder"?

**Comment by andycochran** [comment]
It feels… wrong to add DCP-generated content to a repo for CB-generated content. No?

**Comment by jorgeh01** [comment]
I agree... we can create a new folder "resources-maps" with the following folders:

"landuse"
"censustracts"
"politicaldistricts"
"basemaps"

**Comment by jorgeh01** [comment]
@allthesignals content is ready just need someone to create the repo with above structure :)

**Comment by chriswhong** [comment]
Created new repo `labs-cd-files`
