### ISSUE TITLE
[Waterfront] Resiliency Indicators: Population and Land Mass

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-community-portal#287]

**Comment by andycochran** [comment]
Need data in the model.

**Comment by andycochran** [comment]
I've updated the Carto dataset:

- `current_fp_pop`
- `future_fp_pop`
- `current_fp_area`
- `future_fp_area`
- `current_fp_bldg`
- `cd_tot_bldgs`
- `current_fp_resunits`
- `cd_tot_resunits`
