### ISSUE TITLE
Resiliency Indicators: Comparative Charts

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-community-portal#288]
- [ ] # Buildings 
- [ ] # Dwelling Units

Involves either extending existing chart or duplicating it to add stacked bars showing current FP/future FP/ CD total on the same bar

**Comment by trevorj11** [comment]
[Coastal Flood Resiliency_IntroBlurb.docx](https://github.com/NYCPlanning/labs-community-portal/files/1260558/Coastal.Flood.Resiliency_IntroBlurb.docx)

**Comment by trevorj11** [comment]
[PFIRMs_CDsummary.xlsx](https://github.com/NYCPlanning/labs-community-portal/files/1260710/PFIRMs_CDsummary.xlsx)

This file contains all data for what we are calling the "Current Floodplain" -- columns in red are the ones to include.

**Comment by trevorj11** [comment]
[PFIRMs_CDsummary.xlsx](https://github.com/NYCPlanning/labs-community-portal/files/1260839/PFIRMs_CDsummary.xlsx)

Please see this revised version.

**Comment by trevorj11** [comment]
[PFIRMs_CDsummary.xlsx](https://github.com/NYCPlanning/labs-community-portal/files/1261058/PFIRMs_CDsummary.xlsx)

Version 3

**Comment by andycochran** [comment]
I've updated the Carto dataset:

- `current_fp_pop`
- `future_fp_pop`
- `current_fp_area`
- `future_fp_area`
- `current_fp_bldg`
- `cd_tot_bldgs`
- `current_fp_resunits`
- `cd_tot_resunits`

**Comment by andycochran** [comment]
Closing this & nixing its size in favor of #301.
