### ISSUE TITLE
Format CD dropdown neighborhoods list

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-community-portal#29]
@chriswhong mentioned the CD Boro + CD # should be the "main event", with the neighborhoods as a subheader. This applies to the dropdown typeahead.

**Comment by andycochran** [comment]
Where do we have control over the markup that `power-select` outputs?

**Comment by allthesignals** [comment]
@andycochran :
```
{{#power-select}}
// should be here
{{/power-select}}
```

**Comment by andycochran** [comment]
Addressed in #36.
