### ISSUE TITLE
Add i icon for "Built Environment" subsections

### ISSUE THREAD

**Issue by jorgeh01** [NYCPlanning/labs-community-portal#315]
Land Use
Zoning
Facilities
Community Assets

**Comment by jorgeh01** [comment]
@andycochran @allthesignals Tried adding myself, forthcoming on PR

**Comment by andycochran** [comment]
@jorgeh01, was this addressed by https://github.com/NYCPlanning/labs-community-portal/commit/1d1cd8fe6e18f881cff5ba4010f677f97faee959 ?

**Comment by jorgeh01** [comment]
@andycochran Yes! For the most part, still need to made a few additions/edits.

**Comment by jorgeh01** [comment]
Resolved via PR
