### ISSUE TITLE
ScrollTop

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-community-portal#32]
Need to scroll to top when changing between routes. Currently, if you scroll down then switch from one District to another, the page stays scrolled and you don't see the new District's header.

**Comment by chriswhong** [comment]
+1

**Comment by andycochran** [comment]
Note: We considered this a feature — that you can stay on the same section while switching between profiles and compare CDs — and didn't prioritize this. However, now that we have a About (and Home) page, this is more of a problem. When you scroll to the end of About and switch to a profile, you're at the end of the profile. And vice versa. This is very awkward. 

There are two solutions: 
- Always scrollTop on route change. 
- Know what the routes you're going from/to are. If they're not both profiles, scrollTop. 

However, without testing (or at least asking users) we don't truly know which method is the preferable UX.

**Comment by andycochran** [comment]
Also note: Keeping the page scroll position when switching profiles works for sections that have explicit heights. But the sections that have fluid heights (CB, Projects, Resources) will jump around on route change.

**Comment by kerrygathers** [comment]
I still really like toggling between CDs to compare features without scrolling, so if we can salvage that by differentiating between routes, that sounds ideal. But the bouncing around that happens with the projects and resources sections is kind of annoying. Are you suggesting formal testing with users? @jorgeh01 @amirapu and I could probably put together a group of different types of users.

**Comment by andycochran** [comment]
After today's demo, there seems to be overwhelming support for keeping the scroll position when switching profiles. So we should go with the second solution above. But user testing is a good idea to make sure the page jump on lower-down sections isn't jarring for users.
