### ISSUE TITLE
Set Map default view based on route

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-community-portal#322]
When landing on a profile page, the default for all maps is a citywide view.  All maps then animate their view change, but have already requested resources at the zoomed out view.  

To save some async requests for tiles, and the webGL work of animating many maps, let's set the initial view based on the route.

Another enhancement here would be to eliminate animated movements on the maps in the content area, so they only load what is needed for the view.

**Comment by andycochran** [comment]
This is done via #327, right?
