### ISSUE TITLE
Height of Zoning chart

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-community-portal#333]
The bars in the zoning chart could be slimmer. 

- [x] Add ability to set a height parameter on these charts
- [x] Vertically align the chart to the middle of the map (as is done with the facilities map/legend)

It's confusing when they're taller than they are wide: 
![image](https://user-images.githubusercontent.com/409279/29978145-edb52dea-8f0d-11e7-8453-73403fc333d2.png)

Manhattan 1 uses the most bars, so it can be used to decide what the height of the chart should be: 

![image](https://user-images.githubusercontent.com/409279/29978093-c4ed8894-8f0d-11e7-8c74-e4182a09149f.png)

**Comment by chriswhong** [comment]
Addressed in #355, right?

**Comment by allthesignals** [comment]
@chriswhong what do you mean? Also not sure how this should be fixed. You should be able to override the height parameter, but I can check that.
