### ISSUE TITLE
Remove geometries that are not really CDs?

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-community-portal#34]
The community districts dataset we are using for mapping includes some geometries that are parks or other irregular CDs, such as Queens CD 82:

![labscommunityportal_](https://user-images.githubusercontent.com/1833820/28941975-b877e9cc-7867-11e7-97ef-46f81358c805.png)

Should we exclude these?

**Comment by chriswhong** [comment]
According to @andycochran the customer has already asked that they be removed

**Comment by andycochran** [comment]
List of JIAs not to include: 
http://www1.nyc.gov/site/planning/community/jias-sources.page

**Comment by chriswhong** [comment]
Closed by #43
