### ISSUE TITLE
Revised building typologies heading

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-community-portal#344]
See https://nycplanning.slack.com/files/allanz/F6XBZL4BX/-.txt

**Comment by andycochran** [comment]
- 1–2 Family Homes
- Small Apartments (≤ 5 units, < 5 stories)
- Large Apartments (> 5 units, 5+ stories)
- Mixed-use Apartments
- Commercial
- Manufacturing
- Public Facilities, Institutions, Other

^ approved by Waterfront
