### ISSUE TITLE
Text edits

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-community-portal#346]
See https://nycplanning.slack.com/files/trevorj/F6XD531QD/floodplain_section_text_edits.docx

**Comment by andycochran** [comment]
Addressed in https://github.com/NYCPlanning/labs-community-portal/commit/5b7a6228a2357d758a2adb65efff0369b83b0b99 — except for the following additions to the charts: 

> Age of Buildings in Floodplain
> These counts are grouped based on important dates in the history of NYC’s land-use and floodplain regulation. 1961 marked the establishment of the city’s current zoning resolution, 1983 marked the adoption of Flood Insurance Rate Maps for the first time, and 2013 included the creation of revised Flood Insurance Rate Maps and the adoption of special zoning regulations for flood hazard areas. 
> 
> Basements in Floodplain
> These are counts of buildings that are known to have basements in the floodplain. Basements are among the most flood vulnerable areas of a building, so it is important to understand where they exist and what uses or mechanical systems they may contain.   

^ If these are shortened, we can add them inline with the charts. As-is, they should maybe be added to the about page.

**Comment by andycochran** [comment]
Reopening. Need to solve Age/Building indicator clarification.

**Comment by andycochran** [comment]
Working on this is new branch: `about-section-links`.
