### ISSUE TITLE
Population Pyramid Updates

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-community-portal#348]
- [x] Inconsistent rectangle rounding (one side is rounded, one side is square
- [ ] No legend... which color is male, which is female
- [ ] Show hard numbers instead of percentages

**Comment by allthesignals** [comment]
@chriswhong @kerrygathers they are expressed as percentages in the data profile - we'll just need to compute the counts from total population or change the dataset.

**Comment by allthesignals** [comment]
Preview of using estimates instead of percentages (with estimates computed using pop_11_15_acs column)
![image](https://user-images.githubusercontent.com/5004319/30006164-605d7934-90c0-11e7-884e-e8f6e53d2b84.png)

**Comment by jorgeh01** [comment]
See #371
