### ISSUE TITLE
&mdash broken in several locations (content)

### ISSUE THREAD

**Issue by jorgeh01** [NYCPlanning/labs-community-portal#356]
code "&mdash" broken in:

Zoning TOOLTIP
Neighborhood Studies and Plans TOOLTIP
Community-Based Plans TOOLTIP

**Comment by jorgeh01** [comment]
@andycochran  I can make changes and close out issue if required.

**Comment by andycochran** [comment]
It should be `&mdash;` (with the closing semicolon).

**Comment by jorgeh01** [comment]
Closed with PR
