### ISSUE TITLE
CPC Reports link

### ISSUE THREAD

**Issue by kerrygathers** [NYCPlanning/labs-community-portal#364]
Add link to CPC reports list by CD, which is included in current Community Portal.

**Comment by chriswhong** [comment]
"City Planning Commission Decisions" <--- Subsection Title
"Search CPC Reports" < --  Button text

@jorgeh01 Add tooltip text

**Comment by jorgeh01** [comment]
Per slack "City Planning Commission (CPC) Reports are the official records of actions taken by the CPC"

**Comment by chriswhong** [comment]
Closed by 3a23947e5e2ed95ac887766b2ea70929867fab9f

**Comment by amirapu** [comment]
Move to Projects Section

**Comment by chriswhong** [comment]
Hotfixed in b53453fa Move CPC reports link to Projects Section
