### ISSUE TITLE
Move New Waterfront Revitalization Plan to Studies & Plans

### ISSUE THREAD

**Issue by kerrygathers** [NYCPlanning/labs-community-portal#366]
New Waterfront Revitalization Plan should be moved from Community-Based Plans/197-a list to Neighborhood Studies & Plans list. It should appear for all CDs.

**Comment by chriswhong** [comment]
Completely remove existing "Comprehensive Manhattan Waterfront Plan" and "New Waterfront Revitalization Program"  add two new links provided by Mary Kimball, add them to  Neighborhood studies and plans

**Comment by chriswhong** [comment]
WRP: http://www1.nyc.gov/assets/planning/download/pdf/applicants/wrp/wrp-2016/nyc-wrp-full.pdf

**Comment by chriswhong** [comment]
NYC Vision2020 Comprehensive Waterfront Plan here: http://www1.nyc.gov/site/planning/plans/vision-2020-cwp/vision-2020-cwp.page.

**Comment by chriswhong** [comment]
Implemented in the DB, no code change necessary, closing
