### ISSUE TITLE
Move DOB Permit Search

### ISSUE THREAD

**Issue by kerrygathers** [NYCPlanning/labs-community-portal#367]
Move DOB permit search button out of community-based plan/197-a box to its own section below. Planning Coordination to write tooltip.

**Comment by chriswhong** [comment]
Move it out of the box it currently sits in, make it a lone button.  Make the button say "As-of-right permits"

**Comment by chriswhong** [comment]
"Building information and permits" <-- Subsection Title
"View BISweb" <--- Button Text
