### ISSUE TITLE
Update CSV download

### ISSUE THREAD

**Issue by kerrygathers** [NYCPlanning/labs-community-portal#369]
Update CSV download to include all data fields. Download should also include data dictionary (@kerrygathers to complete data dictionary)

**Comment by allthesignals** [comment]
Addressed by d70c363c

**Comment by allthesignals** [comment]
Waiting for data dictionary

**Comment by kerrygathers** [comment]
Data dictionary uploaded on slack

**Comment by chriswhong** [comment]
Closed by a86680bdc5eeabae3d622f936d0770bbbe2802a2
