### ISSUE TITLE
View all NYC Studies links to a wrong page

### ISSUE THREAD

**Issue by CeciliaCY** [NYCPlanning/labs-community-portal#380]
The current link goes to places which is not a page listing all nyc studies. You can either go to [studies landing page](http://www1.nyc.gov/site/planning/plans/proposals-studies.page) or adding two entries like 

[View all Manhattan Studies](http://www1.nyc.gov/site/planning/plans/manhattan.page) 
[View all Citywide Studies](http://www1.nyc.gov/site/planning/plans/city-wide.page)

**Comment by kerrygathers** [comment]
Thanks, @CeciliaCY! I'll get that fixed.

**Comment by kerrygathers** [comment]
PR #375
