### ISSUE TITLE
JS broken in Chrome 61

### ISSUE THREAD

**Issue by afeld** [NYCPlanning/labs-community-portal#383]
![screen shot 2017-09-12 at 10 41 45 pm](https://user-images.githubusercontent.com/86842/30357561-47f2d55c-980d-11e7-8e0c-cec27be736ab.png)

Chrome version 61.0.3163.79 (Official Build) beta (64-bit), with all extensions disabled. Not seeing the issue in Safari or Firefox.

**Comment by chriswhong** [comment]
This is due to a `<` in a carto SQL api call that is not url encoded, as noted in the warning in the screenshot above.  Hotfixed in 6040a0acd2b4ae78b0e918a5059b001a3fb74b88
