### ISSUE TITLE
Populate missing entries in waterfront table

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-community-portal#386]
Kerry will take care of data update, need to populate the missing entries in the table.

Add logic to show "n/a" when values are null.

**Comment by chriswhong** [comment]
Data will be in number format, add logic to show 200000 as "$200k +"  for  "Median Household Income in the Floodplain"

**Comment by andycochran** [comment]
Closed by https://github.com/NYCPlanning/labs-community-portal/commit/28026d8ab18844da2480ecb8930d006bb0a3760b
