### ISSUE TITLE
Add intro text for Basements in Floodplain and Buildings by Adjacency

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-community-portal#389]
Was shared in slack, someone find it and add it here.

**Comment by allthesignals** [comment]
Basements in Floodplain
Basements are highly vulnerable to flooding and can lead to higher retrofitting costs.    
Attached/Detached Residential Buildings in Floodplain
Buildings that are fully or partially attached are harder to elevate or retrofit to minimize flood risk.

**Comment by chriswhong** [comment]
Closed by a7a7a277cf7ace80cde45fddbacc3acb83a9e082
