### ISSUE TITLE
[Land Use Chart] slow renders potentially misleading 

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-community-portal#39]
When you change between Community Districts, the Land Use Map updates quickly. But there's a lag to the Land Use Chart. So momentarily, you can see a mismatched map/chart. If something should cause this to take a long time (slow connection/device?), you could be misled by the mismatched data. 

Consider hiding the chart on click, and bringing it back once its loaded. 

<img src="https://www.manpower.com/CandidateExperienceStaticTheme/themes/CEHomeTheme/img/loading.gif" width="48">

**Comment by allthesignals** [comment]
This might be a way to handle the awkwardness: https://github.com/danmcclain/ember-deferred-content.

**Comment by allthesignals** [comment]
> ember-deferred-content takes the promise you need to resolve to show your content, and yields 4 subcomponents that you can use to show content during the different states of your promise

**Comment by chriswhong** [comment]
Closed by #45
