### ISSUE TITLE
LUCATS feed showing same info for Active and Completed Applications

### ISSUE THREAD

**Issue by jorgeh01** [NYCPlanning/labs-community-portal#405]
List of applications not filtered by "Active" or "compelted"

**Comment by chriswhong** [comment]
This was an issue with `labs-lucats-proxy`, and was resolved in https://github.com/NYCPlanning/labs-lucats-proxy/commit/394851879c2cd435db68870eb1ef964c62ae4db9

**Comment by chriswhong** [comment]
This

**Comment by chriswhong** [comment]
Fixed with https://github.com/NYCPlanning/labs-lucats-proxy/issues/2
