### ISSUE TITLE
Section link bug in Chrome

### ISSUE THREAD

**Issue by kerrygathers** [NYCPlanning/labs-community-portal#407]
Section links only direct you to the right section from the top of the page. From anywhere else on the page, all links just drag you incrementally further down the page. First found it in Chrome, but it happens in Firefox and IE too. Links work in Safari.

**Comment by allthesignals** [comment]
Addressed in #f2547f04

**Comment by chriswhong** [comment]
I undid some commits that happened after db7bdd676ed681807b39ee7ca0e769f788973a30,  this issue is resolved, but we lost the scroll-to effect.
