### ISSUE TITLE
Remove beta banner

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-community-portal#409]

**Comment by chriswhong** [comment]
The beta notice was removed, but removing the orange banner completely introduced a lot of CSS issues which were all linked to that extra height in the header.  Need to remove the bar and clean up layout.

OR

We keep the bar there as empty and use it for alerts...

**Comment by andycochran** [comment]
Fixed in https://github.com/NYCPlanning/labs-community-portal/commit/fe7359405918dd5c4deffb29a26498b42e1c2d2d.
