### ISSUE TITLE
Updated floodplain tables with revised Census/ACS data

### ISSUE THREAD

**Issue by allanz-dcp** [NYCPlanning/labs-community-portal#410]
[Community_District_Profiles_Floodplain_Tables_Final_091517.zip](https://github.com/NYCPlanning/labs-community-portal/files/1307784/Community_District_Profiles_Floodplain_Tables_Final_091517.zip)

Attached table includes revised corrected data for floodplain characteristics. Additional new field(s) at end is "Owner Occupied Units Cost Burdened"

**Comment by chriswhong** [comment]
New data added to DB, Owner Occupied Units Cost Burdened implemented in 4ca9854cc0c23f0d281d1ba0b4601634f4252f40

I was also able to add special handling for the "$200,000+" mhhi in Brooklyn 2
