### ISSUE TITLE
Query Params AND hash are used in section nav

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-community-portal#419]
URLs look like http://localhost:4200/queens/6?section=indicators#indicators

We should figure out how to use only one or the other, and it must work (scroll the page to the section) when navigating directly to the site.

**Comment by ryhinchey** [comment]
@chriswhong 👋 I've been looking through this Ember app and have a fix for this issue.  Do you prefer I fork and create a PR?

**Comment by ryhinchey** [comment]
Cool - here's the PR
https://github.com/NYCPlanning/labs-community-portal/pull/439

**Comment by andycochran** [comment]
Your solution worked perfectly, @ryhinchey. Merged. Thanks so much for the PR.
