### ISSUE TITLE
Draft Content for Landing Page

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-community-portal#42]
![labscommunityportal_and_slack_-_nycplanning](https://user-images.githubusercontent.com/1833820/28973415-1e8457ca-7901-11e7-9f5a-5bf3d4d900ca.png)

We need draft content for the landing page.  

- [x] A welcome blurb 
- [x] 3 more specific feature highlights, perhaps with icons

Implied task is to train the client in updating text in HTML.

Issue is done when:

- [ ]  Client can create pull requests with updated content

**Comment by andycochran** [comment]
Need to show client how to do this.
