### ISSUE TITLE
Queen 6 doesn't show Land Use Applications info

### ISSUE THREAD

**Issue by CeciliaCY** [NYCPlanning/labs-community-portal#430]
This section is keeping loading - 
Please check this link - https://communityprofiles.planning.nyc.gov/queens/6?section=projects#projects
And https://lucats.planninglabs.nyc/ulurp/cd/queens/6.json returns nothing

**Comment by chriswhong** [comment]
It looks like there is only one active application for queens 6, and LUCATS shows the application view instead of a table view in this case.  

Created issue in `labs-lucats-proxy`: https://github.com/NYCPlanning/labs-lucats-proxy/issues/4

**Comment by chriswhong** [comment]
Added special handling for single-result community district search in `labs-lucats-proxy` https://github.com/NYCPlanning/labs-lucats-proxy/commit/10a2a30b549bdb120bb7f1be0fdd4cae05703cf2

The result for Queens 6 shows up, though it's missing the latest milestone (can't parse that from the single result page on LUCATS without additional work)
