### ISSUE TITLE
Problems loading LUCATS data

### ISSUE THREAD

**Issue by SarahWhitham** [NYCPlanning/labs-community-portal#434]
While the individual CD pages are loading, there seems to be a problem with loading the LUCATS portion of the page  for Brooklyn CD 4.  Not sure if this is a problem for other CDs.

**Comment by chriswhong** [comment]
Taking a look at this now...

**Comment by chriswhong** [comment]
It was getting a bad cached API response, switched back to `lucats.planninglabs.nyc` and Brooklyn 4 is loading the 2 active projects that it's supposed to.
