### ISSUE TITLE
Replace poverty rate with NYCgov poverty rate

### ISSUE THREAD

**Issue by kerrygathers** [NYCPlanning/labs-community-portal#435]
The Mayor's Office for Economic Opportunity asked us to replace the federal poverty rate with the NYCgov poverty rate, a measurement they designed to incorporate costs of living (housing, healthcare, etc.) and anti-poverty benefits (public housing, SNAP, etc). Jon and Joe Salvo agreed.

- [ ] Update csv with NYCgov poverty rate, MOE, boro and citywide rates
- [ ] Update language in data box and tooltip
- [ ] Update data dictionary
- [ ] Update PDF profiles

**Comment by andycochran** [comment]
- [x] Prepare `poverty-nycgov` branch, make sure @kerrygathers' edits look good in the layout (the provided text is loooong)
- [ ] Merge `poverty-nycgov` into develop
- [ ] Sync the timing of 
  - Carto data update (labs)
  - Deploy to production (labs)
  - PDF updates (@kerrygathers)
