### ISSUE TITLE
Add disclaimer about neighborhood boundaries

### ISSUE THREAD

**Issue by kerrygathers** [NYCPlanning/labs-community-portal#437]
Users have contacted us asking for "official," determinations of neighborhood boundaries. We need to add a disclaimer somewhere saying that neighborhood names and boundaries are not officially designated. Possibly below the neighborhoods bar on each page, or on the About page.

**Comment by andycochran** [comment]
I would suggest adding a section to the about page to describe the stuff above indicators (neighborhoods list, population, demographics). This disclaimer could be included there. 

/cc @amirapu

**Comment by amirapu** [comment]
@andycochran I think that is a good idea. We will do that, in addition though, the Press office would like a disclaimer on all the pages too, can you think about where would be a good place for that? I was thinking we can a (*) after the neighborhoods and have the disclaimer at the bottom of each page

**Comment by andycochran** [comment]
Or we could add a tooltip to the neighborhoods list that contains the disclaimer.

**Comment by kerrygathers** [comment]
@andycochran @amirapu I think a tooltip at the end of the neighborhood list would be sufficient. Any objections?

The language could follow what's on the static profiles: "Neighborhoods may be in multiple districts. Neighborhood names and boundaries are not officially designated."

Is there any easy way to make the tooltip icon white? I think the black icon would look pretty bad on they gray background of the neighborhood list.

**Comment by andycochran** [comment]
The icon should inherit the color of the text it's inline with.

**Comment by andycochran** [comment]
Closed by #449
