### ISSUE TITLE
Apostrophe not displayed in list of issues for Statement of CD Needs

### ISSUE THREAD

**Issue by jorgeh01** [NYCPlanning/labs-community-portal#444]
For Bronx 8 showing "Youth and childrenäó»s services" instead of "Youth and children's services"

**Comment by andycochran** [comment]
![image](https://user-images.githubusercontent.com/409279/33951347-baf237fa-dffc-11e7-8f61-7cb1ee7b0e4a.png)

**Comment by andycochran** [comment]
Fixed in Carto.
