### ISSUE TITLE
Indicator CSV download not working

### ISSUE THREAD

**Issue by kerrygathers** [NYCPlanning/labs-community-portal#445]
The indicator download button returns this error:

<img width="1303" alt="screen shot 2017-10-19 at 3 13 08 pm" src="https://user-images.githubusercontent.com/29131366/31789567-83e0b7ce-b4e0-11e7-8ddc-8c080b69c604.png">

With the update to the NYCgov poverty measure, the csv no longer includes moe_poverty_rate_boro or moe_poverty_rate_nyc. We didn't have that data readily available, and it wasn't being used in the profiles, so I deleted the columns. I assume this is causing the error.

**Comment by allthesignals** [comment]
Closed by 7d9fa1dda81e3ce3cb4b4dc9b2e758ba63da8657
