### ISSUE TITLE
Sticky navigation in profile should be mobile responsive

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-community-portal#47]
Currently it offsets the top in desktop view to make space for the header (which is fixed). In mobile, the header is no longer fixed, so it becomes a floating strip.

**Comment by andycochran** [comment]
Can we just make this sticky for medium-size screens and up? I don't think it's necessary on mobile.

**Comment by allthesignals** [comment]
Of course! Your call what you think is best

**Comment by andycochran** [comment]
Not sure how to do this with [ember-sticky-element](https://github.com/kaliber5/ember-sticky-element). In Foundation, it's a `data-sticky-on="[size]` attribute that matches a breakpoint size defined in `_settings.scss`. Foundation's JS is aware of its CSS breakpoints, but I don't think that's easy to work into ember-sticky-element. So only one solution comes to mind: set explicit `!important` styles that override the plugin's inline styles for small screens only. Ugly but simple. I'll give that a try unless we can think of a better method.

**Comment by allthesignals** [comment]
@andycochran since it's component-based, we can use an [addon](https://github.com/freshbooks/ember-responsive) to expose window sizes to the Ember app (then it's just a conditional in the handlebars). "data-sticky-on" is a custom attribute, so it's related Foundation's JavaScript suite, which we aren't really using for this (we'll need to work on the integration addon to start using FoundationJS). Let me know what you think is best!

**Comment by andycochran** [comment]
Yup. Seems like it's a tradeoff between storing the breakpoints in two places or using `!important` styles.
