### ISSUE TITLE
Basic Application Architecture and Routing

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-community-portal#5]
- [x] Frontend Framework
- [x] Layout/Design Library 
- [x] Client Side Routing between landing page and dc pages

End state: Can "npm start" the application, dev environment exists, can load dummy landing page and navigate to dummy cd pages, ready for layout and other features.

The only routing for this sprint is landing page + 59 cd pages.

**Comment by chriswhong** [comment]
Proposing URL structure like: `{domain}/bronx/1`, `{domain}/brooklyn/6`

**Comment by allthesignals** [comment]
@chriswhong alright, looking for data that maps borough to CD

**Comment by allthesignals** [comment]
Just doing an inner join by centroid of CD intersecting boro polygon: https://cartoprod.capitalplanning.nyc/user/cpp/api/v2/sql?q=SELECT a.borocd, b.boroname FROM ny_community_districts a INNER JOIN ny_boroughs b ON ST_Intersects(ST_Centroid(a.the_geom), b.the_geom)

**Comment by chriswhong** [comment]
const SQL = `
  SELECT the_geom, RIGHT(borocd::text, 2)::int as cd,
  	CASE
    	WHEN LEFT(borocd::text, 1) = '1' THEN 'Manhattan'
      WHEN LEFT(borocd::text, 1) = '2' THEN 'Bronx'
      WHEN LEFT(borocd::text, 1) = '3' THEN 'Brooklyn'
      WHEN LEFT(borocd::text, 1) = '4' THEN 'Queens'
      WHEN LEFT(borocd::text, 1) = '5' THEN 'Staten Island'
    END as boro,
    borocd
  FROM support_admin_cdboundaries
  ORDER BY boro, cd ASC
`;

...gets us a nice `boro` and `cd` without leading zeroes, suitable for display, no JOIN necessary.

**Comment by allthesignals** [comment]
@chriswhong ah, perfect! Didn't know that, thank you! That is much simpler.
