### ISSUE TITLE
Is "Top 3 Community Needs" a bad header?

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-community-portal#55]
The "Top 3 Community Needs" in some CDs are things like: 
- Parks
- Neighborhood preservation
- Affordable housing

^ Those _are_ needs. 

But some are things like: 

- Street flooding
- Traffic

^ Who needs traffic or flooding? 

Maybe there's a better way to phrase it? "Top Issues"?

**Comment by amirapu** [comment]
Hi! Please change title to "Top Three Pressing Issues Identified by the Community Board" Is there a way to program to the name of the board for each page? Also we should include the year which is FY 2018

**Comment by andycochran** [comment]
I've fixed the section title in https://github.com/NYCPlanning/labs-community-portal/commit/89d3107b29ce8fa103c982764458a05108ac04c2. 

@amirapu Do you mean the name of Community Board should be something other than "[Borough] Community Board [number]"?  If so, we could give each District a unique `community_board_name` property. Otherwise, they can be programmatically named as above with the current data.

**Comment by andycochran** [comment]
Ack! The section menu still says "needs." Above commit doesn't fix that. 
![image](https://user-images.githubusercontent.com/409279/29031199-6d04b352-7b5b-11e7-8c4f-4451edcd2139.png)

**Comment by andycochran** [comment]
Remaining piece of this issue will be addressed in #80.
