### ISSUE TITLE
[Feedback] I want to be able to download the source data

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-community-portal#62]
User mentioned wanting to be able to download the data as csv.

Done when:

- [ ] Add 'data' subsection to 'Data & Resources' section on profile pages
- [ ] Add 'Data' section to `/about` page, with info about the data and download links for the entire csv and associated metadata

**Comment by andycochran** [comment]
Another solution: 

A table view of all the data powering the app with a big download button. 

I've prototyped this in a branch: https://github.com/NYCPlanning/labs-community-portal/tree/ac/table-view

![image](https://user-images.githubusercontent.com/409279/29222647-61db557e-7e91-11e7-90f7-cfbbbf13ada2.png)

Other features we could add: 
- when hovering a row, the appropriate district highlights in the map
- when scrolling the table the CD column stays frozen

**Comment by andycochran** [comment]
@allthesignals Is the "big table" method easier now that you've implemented models for Districts & DataProfiles?

**Comment by chriswhong** [comment]
I get the value in a citywide table view vs the layout view with charts, etc on the profiles.  I think the download itself has more value and should be prioritized above another web view.  It also means we need to figure out the display logic for each value in two places instead of one.

**Comment by allthesignals** [comment]
@andycochran I think it's about the same - it's more of a challenge in terms of getting the view right.

**Comment by chriswhong** [comment]
Basic downloads implemented in #233, closing
