### ISSUE TITLE
Comparative chart for key indicators

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-community-portal#63]
Build out comparative CD bar graphs for 8 Key Indicators

Done when: 
- [ ]  A composable chart component exists that shows the indicator across all CDs with the current CD highlighted
- [ ] Chart also shows the same indicator for boroughs and city level (for normalized indicators)

**Comment by allthesignals** [comment]
@kgathers  These are the columns I think I'm using for the comparative charts: 
 - POVERTY_RATE  
 - UNEMPLOYMENT_CD 
 - CRIME_PER_1000  
 - MEAN_COMMUTE 
 - PCT_HH_RENT_BURD
 - PCT_CLEAN_STRTS

You mentioned educational attainment, but I couldn't see that column in the data dictionary.

**Comment by kerrygathers** [comment]
The actual variable is percentage of adults with a bachelor's degree or higher. I think the fiel;d name is PCT_BACH_DEG, or something like that.

**Comment by allthesignals** [comment]
@andycochran how is this going to look? the chart sits under the indicator?

**Comment by andycochran** [comment]
The layout is done in PR https://github.com/NYCPlanning/labs-community-portal/pull/87.

**Comment by chriswhong** [comment]
Closed by #92
