### ISSUE TITLE
Nav Map should have defined neighborhood labels

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-community-portal#65]
This issue is done when:
- [ ] Standard neighborhood labels on the nav map are replaced with a defined set of labels

**Comment by kerrygathers** [comment]
Here's the neighborhood label point file: [Neighborhood_Labels.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5988a75a7d1051001fe82b7f/125516c66e82c728ace21e0d46c69193248a81a69de1b04ca062dc952b432b606b48e13b628ae92dbc56395b4d5a47ab175e0a42f4fc8b28a1b46d708a5903ead7680d73902f0dbefad341eb5ee779c11ac7a4b6984ec6e23c20e7898e4d361b031d81fe5927ed.zip)

**Comment by jorgeh01** [comment]
Resolved
