### ISSUE TITLE
[Typography] Don't put tooltip triggers in <sup>

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-community-portal#69]
These… 
![image](https://user-images.githubusercontent.com/409279/29030458-0f2d641a-7b59-11e7-8a93-ee219f620063.png)

…should match this: 
![image](https://user-images.githubusercontent.com/409279/29030499-30d74f0e-7b59-11e7-8fdf-1d34a3960368.png)

**Comment by chriswhong** [comment]
Will be addressed in #70
