### ISSUE TITLE
Implement Key Indicators Section

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-community-portal#82]
Should include a placeholder for the chart component from #63.  

Done when: 
- [ ] Each profile contains a fully built out Section for Key Indicators. 
- [ ] Each indicator is well styled, readable, and organized in a way that makes sense.

**Comment by allthesignals** [comment]
@andycochran how do you want to tackle this?

**Comment by andycochran** [comment]
Blocked by #80

**Comment by andycochran** [comment]
Like this? 

1. [ ] somebody merges 80 
2. [ ] @allthesignals hooks up all the data in their corresponding containers
3. [ ] @andycochran styles each stat appropriately 

(Or I can probably figure out how to get the data working too.)

**Comment by andycochran** [comment]
I've got the data in there. Working on styling now…

**Comment by andycochran** [comment]
PR https://github.com/NYCPlanning/labs-community-portal/pull/87 closes this. Reassigning to @allthesignals.
