### ISSUE TITLE
[Map] zoom controls missing

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-community-portal#90]
Seems we lost the +/- buttons on the map. 

`.mapboxgl-ctrl-top-left` is empty. 

(Did this happen in the switch to MapboxGL?)

![image](https://user-images.githubusercontent.com/409279/29136568-a80129f2-7d0b-11e7-9b49-fb1f314561dc.png)

**Comment by chriswhong** [comment]
Fixed with the move to MapboxGL
