### ISSUE TITLE
[Data Formatting] pop_change_00_10

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-community-portal#96]
This should indicate the + or - change. 

Currently works great for negative numbers: 
![image](https://user-images.githubusercontent.com/409279/29176552-207ab41c-7dba-11e7-9d25-db6aaf801e85.png)

But positive numbers should be prefixed with a "+". They're currently not: 
![image](https://user-images.githubusercontent.com/409279/29176583-3b731c00-7dba-11e7-9367-bada54ccb11f.png)

Without the "+", this percentage makes no sense.

**Comment by andycochran** [comment]
@chriswhong Is this easy to fix with Numeral.js?

**Comment by chriswhong** [comment]
Easy fix, change numeral template from '0%' to '+0%'

**Comment by chriswhong** [comment]
Closed by #157
