### ISSUE TITLE
Community Board Links

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-community-portal#98]
The Community Board website and email links are empty. Need to give these real data. 

![image](https://user-images.githubusercontent.com/409279/29185167-797927b2-7dd6-11e7-9bff-2fdb87fbc0b1.png)

**Comment by allthesignals** [comment]
Hmmm @kerrygathers is there data for this? Sorry if I missed it, I know you posted some things in Slack. Thanks.

**Comment by chriswhong** [comment]
Closed by #182
